# Generated by Django 5.2.4 on 2026-01-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='コース名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('ai_context', models.JSONField(blank=True, default=dict, help_text='生成時の気分や条件（プロンプト等）')),
                ('tags', models.JSONField(blank=True, default=list, help_text="['公園', '静か'] などのタグ")),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, verbose_name='公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSpotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='巡回順序')),
                ('estimated_stay_min', models.PositiveIntegerField(default=0, verbose_name='滞在予定時間(分)')),
                ('course_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.coursetemplate')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='UserPrivacyMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=200, help_text='半径(メートル)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_masks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新しい散歩', max_length=255)),
                ('trajectory', models.JSONField(default=list, verbose_name='移動経路データ')),
                ('total_distance_m', models.FloatField(default=0.0, verbose_name='総移動距離(m)')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('course_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coursetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='walk_photos/')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('walk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.walksession')),
            ],
        ),
        migrations.CreateModel(
            name='WalkSpotVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255, verbose_name='場所名')),
                ('place_id', models.CharField(blank=True, help_text='Google/MapboxのPlaceID', max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('stay_duration_sec', models.PositiveIntegerField(default=0)),
                ('walk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.walksession')),
            ],
        ),
    ]
