# Generated by Django 5.2.4 on 2025-11-29 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('relax', 'リラックス'), ('hungry', 'グルメ'), ('active', 'アクティブ')], default='relax', max_length=20)),
                ('default_distance_m', models.PositiveIntegerField(blank=True, help_text='想定総距離（メートル）', null=True)),
                ('default_duration_min', models.PositiveIntegerField(blank=True, help_text='想定所要時間（分）', null=True)),
                ('move_mode', models.CharField(default='walk', help_text='walk / car など', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='システム提供コースなら null, ユーザー作成ならそのユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSpotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='コース内の順番（1始まり）')),
                ('name', models.CharField(max_length=100)),
                ('place_id', models.CharField(help_text='Google Places API の place_id。長期保存はこのID中心に行う。', max_length=100)),
                ('category', models.CharField(blank=True, help_text='cafe / park / shrine など任意のカテゴリ', max_length=50)),
                ('stay_time_min', models.PositiveIntegerField(blank=True, help_text='想定滞在時間（分）。未設定ならデフォルト扱い。', null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.coursetemplate')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
