# Generated by Django 5.2.4 on 2025-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coursetemplate_coursespottemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='内部用コード。例: walk, meal, sightseeing など', max_length=30, unique=True)),
                ('label', models.CharField(help_text='表示名。例: 散歩, 食事, 観光 など', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='move_mode',
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='title',
            field=models.CharField(blank=True, help_text='任意。未設定の場合は日付_シーケンス番号などを自動付与する想定。', max_length=100),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='modes',
            field=models.ManyToManyField(blank=True, help_text='散歩 / 食事 / 観光 など複数選択可', related_name='courses', to='api.coursemode'),
        ),
    ]
