# Generated by Django 5.2.4 on 2025-12-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coursemode_remove_coursetemplate_move_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_distance_m', models.IntegerField(blank=True, help_text='歩いた距離（メートル）。クライアント側で計算して送信想定。', null=True)),
                ('total_duration_sec', models.IntegerField(blank=True, help_text='散歩時間（秒）。ended_at - started_at でも算出可能。', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_template', models.ForeignKey(blank=True, help_text='この散歩が紐づくコーステンプレ（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_sessions', to='api.coursetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkSpotVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, help_text='Google などの place_id。無ければ空でOK。', max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('arrived_at', models.DateTimeField()),
                ('left_at', models.DateTimeField()),
                ('stay_duration_sec', models.IntegerField(blank=True, help_text='滞在時間（秒）。サーバ側で left - arrived から計算してもよい。', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_spot_template', models.ForeignKey(blank=True, help_text='テンプレ上のスポットに対応する場合のみ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_spot_visits', to='api.coursespottemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_visits', to='api.walksession')),
            ],
            options={
                'ordering': ['session', 'arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='walk_photos/')),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.walksession')),
                ('spot_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.walkspotvisit')),
            ],
            options={
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
    ]
